### ISSUE TITLE
query for Properties checks limits name length.

### ISSUE THREAD

**Issue by hwchen** [jazzido/mondrian-rest#26]
- Properties currently have a check which prevents names from being over 3 segments long, and including the shared dim name would violate this (as would just having a hierarchy name, actually). See https://github.com/jazzido/mondrian-rest/blob/public/lib/mondrian_rest/api_helpers.rb#L90 and see specific issue #25 . Properties actually work with the less-qualified name (without the shared dim) but this creates an inconsistency in naming schemes.

**Comment by hwchen** [comment]
@jazzido wasn't entirely sure, but also wanted to check if the `caption` option would also be affected by this check.

**Comment by jazzido** [comment]
This should be fixed now. I'll ship it with the new release. If you need it sooner, you can point to the repo on your `Gemfile` (like we did before)
