### ISSUE TITLE
[Feature] Sorting and ordering results

### ISSUE THREAD

**Issue by jspeis** [jazzido/mondrian-rest#29]
For Data USA:

* [x] Ability to choose a Measure on which the data will be sorted
* [x] Ability to specify sort order (e.g. descending / ascending)

This will be helpful for querying results by `Metric` in `Descending` order, for example

**Comment by jazzido** [comment]
@jspeis do we need to sort on multiple "columns"? If so, how would you specify that behavior?

**Comment by jspeis** [comment]
Multiple columns not required. Could be cool if easy to do, otherwise no worries

**Comment by jazzido** [comment]
Also, do we need to support sorting by the members of a dimension? (e.g. Counties in alphabetical order)

**Comment by jspeis** [comment]
yes
