### ISSUE TITLE
[Feature] Limiting results

### ISSUE THREAD

**Issue by jspeis** [jazzido/mondrian-rest#30]
For Data USA: The ability to limit the number of results returned by the API (e.g. in conjunction with #29 could be used to return top 5 results on some metric)

**Comment by jazzido** [comment]
To clarify: it only makes sense to implement this in the 'tidy' formats that `mondrian-rest` can generate, i.e.: XLS, CSV and JSONRecords. The default JSON response format is multidimensional, so there's no way (AFAICT) to limit/offset the result set.

**Comment by jspeis** [comment]
Seems like it's possible using the `Generate` function? https://docs.microsoft.com/en-us/sql/mdx/generate-mdx
